name: scanb
channels:
  - bioconda
  - conda-forge

dependencies:
  - bowtie2=2.4.1
  - fastp=0.20.1
  - hisat2=2.2.1
  - samtools=1.9
  - stringtie=2.1.4
  - conda-forge::r-base=3.6.1
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-caret=6.0
  - conda-forge::r-e1071=1.7
