Bootstrap: docker
From: nfcore/base:1.9

%files
    environment.yml /
    /data/bnf/sw/sentieon/sentieon-genomics-201911 /opt

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin clean -a

%environment
	PATH=/opt/conda/envs/scanb/bin:/opt/sentieon-genomics-201911/bin/:/opt/bin:/opt/conda/envs/py3-env/bin:$PATH
    PICARD_HOME=/opt/conda/envs/CMD-WGS/share/picard-2.23.8/

%labels
    MAINTAINER Markus Johansson <markus.h.johansson@skane.se>
    DESCRIPTION Singularity contianer for RNAseq pipeline
    VERSION v0.0.1

%help
    This is container intended to be used by nextflow with the XXX pipeline.
