Bootstrap: docker
From: nfcore/base:1.10.2

%files
    environment.yml /
    /data/bnf/sw/sentieon/sentieon-genomics-201911/bin /opt

%post
    /opt/conda/bin/conda env create -f /environment.yml
    /opt/conda/bin/conda clean --all
    /opt/conda/bin/conda init bash

%environment
	PATH=/opt/conda/envs/scanb/bin:/opt/sentieon-genomics-201911/bin/:/opt/bin:$PATH

%labels
    MAINTAINER Markus Johansson <markus.h.johansson@skane.se>
    DESCRIPTION Singularity contianer for RNAseq pipeline
    VERSION v0.0.1

%help
    This is container intended to be used by nextflow with the SCANB pipeline.
